### ISSUE TITLE
Janet Integration for this issue tracker

### ISSUE THREAD

**Issue by pupnewfster** [pupnewfster/GalaxyGamingIssues#56]
# Description

To make Janet create an issue for the most popular suggestions on the forums, or if there are detailed enough reports in the bug_reports slack channel. This can also include replying on the forums/locking a post when an issue is closed here.

- [ ] Parses #bug_reports channel and creates issues based on detailed messages.
- [ ] Parses suggestions on the forums using the REST API to create issues when they have a positive enough reaction (+1, or other positive reactions).
- [ ] Close suggestions on forums with explanation why and lock.
- [x] ~~Maybe when a bug report that was posted in Slack gets fixed, post a message to the #bug_reports channel saying it is now fixed.~~
- [ ] ~~Send reminders to people on Slack if they have an issue assigned to them.~~
- [ ] ~~When Staff applications get accepted automatically send a slack invite to the users email.~~

## Server, select all that apply

- [x] Website
- [x] ~~Slack~~
- [x] GitHub
- [x] Discord

**Comment by pupnewfster** [comment]
Progress can be viewed here [Janet Issue Tracker](https://github.com/pupnewfster/JanetIssueTracker)

**Comment by pupnewfster** [comment]
Added about auto-inviting accepted staff to slack. Also we potentially could later make a bug reports channel in the discord that Janet could listen to as well.
